### ISSUE TITLE
Can't ask questions on Firefox

### ISSUE THREAD

**Issue by madsmtm** [liveask/liveask#74]
I'm not sure exactly what's wrong here, probably something specific to my setup.

The console shows the following on load:
```
Uncaught TypeError: img.parentNode is null
```

And the following when I click the "Ask a question" button (nothing happens when I click the button).
```
Uncaught TypeError: navigator.sendBeacon is not a function
```

So might be related to that?

**Comment by extrawurst** [comment]
ok at least i can reproduce it now with this: https://mattermost.atlassian.net/browse/MM-58777

**Comment by extrawurst** [comment]
any idea why this is disabled on your setup?

**Comment by madsmtm** [comment]
No idea, likely because I fiddled with some setting I didn't understand years ago

**Comment by extrawurst** [comment]
anyhow, this will soon be fixed
